DROP DATABASE IF EXISTS ordersdb;
CREATE DATABASE ordersdb;
USE ordersdb;
CREATE TABLE IF NOT EXISTS ordersdb.orders (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(64) NOT NULL,
    ISIN VARCHAR(64) NOT NULL,
    Amount INTEGER NOT NULL,
    Price DOUBLE NOT NULL,
    State INTEGER NOT NULL
);
