services:
  mongoservice:
    image: mongo:latest
    restart: always
    #environment:
    #  MYSQL_DATABASE: mongodb
    #  MYSQL_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
    # Mounts the init.sql file to docker entrypoint - runs the query on startup
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mongo-data:/data/db


  order-service:
    image: henriquerebolho/order-service-extended
    #build: ./order-service
    ports:
      - "6010:6010"
    depends_on:
      - mongoservice


  confirmation-service:
    image: henriquerebolho/confirmation-service-extended
    #build: ./confirmation-service
    ports:
      - "4000:4000"
    deploy:
      replicas: 2

volumes:
    mongo-data: