# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: confirmation-service  # must be unique within namespace
  labels:         # organize and categorize
    app: confirmation-service
spec:             # desired status of the deployment
  replicas: 1
  selector:       # label query over a set of resources 
    matchLabels:
      app: confirmation-service   # It must match the pod template's labels
  template:       # describes the data a pod should have when created from a template
    metadata:
      labels:
        app: confirmation-service
    spec:         # specification of the desired behavior of the pod
      containers:
        - name: confirmation-service-container
          image: confirmation-service:local
          imagePullPolicy: Never
          ports:
          - name: grpc
            containerPort: 4000
          readinessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 10
            periodSeconds: 10
