# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service  # must be unique within namespace
  labels:         # organize and categorize
    app: order-service
spec:             # desired status of the deployment
  replicas: 1
  selector:       # label query over a set of resources 
    matchLabels:
      app: order-service   # It must match the pod template's labels
  template:       # describes the data a pod should have when created from a template
    metadata:
      labels:
        app: order-service
    spec:         # specification of the desired behavior of the pod
      containers:
        - name: order-service-container
          image: order-service:local
          imagePullPolicy: Never
          env:
          - name: MONGODB_URI
            value: mongodb://db-service:27017/orders
          - name: CONFIRMATION_SERVICE_ADDRESS
            value: confirmation-service-service:4000
          ports:
          - name: http
            containerPort: 6010
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10

