apiVersion: v1
kind: Service
metadata:
  name: confirmation-service-service
spec:
  selector:
    app: confirmation-service
  ports:
    - name: grpc
      port: 4000
      targetPort: 4000
      protocol: TCP
  type: ClusterIP
