apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: db-service # service must exist before the StatefulSet, responsible for network identity of the set
  replicas: 1 # only 1 database
  selector:
    matchLabels: 
      app: mongodb
  template:   # object that describes the pod that will be created if insufficient replicas are detected
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports: 
          - name: mongodb
            containerPort: 27017
          volumeMounts:         # list of claims that pods are allowed to reference
          - name: mongo-data
            mountPath: /data/db
  volumeClaimTemplates:   # list of claims that pods are allowed to reference
    - metadata:
        name: mongo-data
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
